### ISSUE TITLE
assets:precompile fails (rack_dev_mark)

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1704]
tracks 9a69b170fe366e85d14ab1c2ba82645ad57f5f46
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
Bundler version 1.3.5

```
$ bundle exec rake assets:precompile
rake aborted!
NoMethodError: undefined method `rack_dev_mark' for #<Rails::Application::Configuration:0x00000003b51398>
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie/configuration.rb:95:in `method_missing'
/home/cotto/git/tracks/config/environments/development.rb:29:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie.rb:210:in `instance_eval'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie.rb:210:in `configure'
/home/cotto/git/tracks/config/environments/development.rb:1:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:593:in `each'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:593:in `block in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
/home/cotto/git/tracks/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:276:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:379:in `block in run_tasks_blocks'
/var/lib/gems/1.9.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:55:in `block (2 levels) in def
Tasks: TOP => environment
(See full trace by running task with --trace)
```

```
$ bundle exec rake assets:precompile --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `rack_dev_mark' for #<Rails::Application::Configuration:0x000000034a2358>
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie/configuration.rb:95:in `method_missing'
/home/cotto/git/tracks/config/environments/development.rb:29:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie.rb:210:in `instance_eval'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/railtie.rb:210:in `configure'
/home/cotto/git/tracks/config/environments/development.rb:1:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:593:in `each'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/engine.rb:593:in `block in <class:Engine>'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
/usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:209:in `block in each_strongly_connected_component_from'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `each'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
/usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
/usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
/usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:300:in `initialize!'
/home/cotto/git/tracks/config/environment.rb:5:in `<top (required)>'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/1.9.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:276:in `require_environment!'
/var/lib/gems/1.9.1/gems/railties-4.1.4/lib/rails/application.rb:379:in `block in run_tasks_blocks'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/sprockets-rails-2.1.3/lib/sprockets/rails/task.rb:55:in `block (2 levels) in define'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => environment
```

**Comment by khyox** [comment]
In the (very useful!) installation doc, in the section **Populate your database with the Tracks schema**, you say *Open a terminal and change into the root of your Tracks directory. Enter the following command: `bundle exec rake db:migrate RAILS_ENV=production`*. But in the next section the `RAILS_ENV=production` is missing from the command suggested, which led me to this issue (I am using Rails 4.1.8). Please, would you consider changing the doc to avoid further this problem? Sorry for bothering! :sweat_smile:

**Comment by dnrce** [comment]
@khyox I assume you're installing from `master`? The docs have been updated for 2.3 and later -- they're in `/doc` -- but getontracks.org links to the 2.2.3 docs because that's the most recent stable version. Does that clear things up? Or am I missing something?

**Comment by khyox** [comment]
@dnrce Yes, thanks for your answer and sorry indeed! I was messing with links coming from getontracks.org. :sweat:

**Comment by dnrce** [comment]
@khyox No worries. It's definitely a little confusing. I've been experimenting with readthedocs.org to help make the versioned docs a bit more accessible, but that's not ready for prime time yet.
