### ISSUE TITLE
Getting an error : ActionController::RoutingError (No route matches [GET] “/tracks”) while installing TracksApp

### ISSUE THREAD

**Issue by anatoly314** [TracksApp/tracks#1930]
Hi, I'm duplicating my question from SO: http://stackoverflow.com/questions/32796556/getting-an-error-actioncontrollerroutingerror-no-route-matches-get-trac  maybe somebody could help me? 

I'm trying to install [Tracks][1] on Nginx + Passenger and getting the following error when trying to access the site:
`The page you were looking for doesn't exist.`
When I check `/log/production.log` I see the following record:

    ActionController::RoutingError (No route matches [GET] "/tracks"):
      actionpack (4.1.11) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
      actionpack (4.1.11) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.1.11) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.1.11) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.1.11) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.1.11) lib/active_support/tagged_logging.rb:26:in `tagged'

I suspect that issue that I trying to use sub-uri within my domain, i.e. `www.example.com/tracks`, for example in [Redmine][2] I need to add the following lines at `environment.rb`:

    RedmineApp::Application.routes.default_scope = { :path => '/redmine', :shallow_path => '/redmine' }
    ...
    Redmine::Utils::relative_url_root = "/redmine"

Perhaps I need to make same changes at Tracks but I don't know rails.

This is config from `nginx.conf` responsible for this Tracks:

    location /tracks {
               passenger_enabled on;
               alias   /opt/tracks/public;
               index  index.html index.htm;
           }

Thank you in advance.

  [1]: https://github.com/TracksApp/tracks
  [2]: http://www.redmine.org/

**Comment by anatoly314** [comment]
Ok, thanks to my friend, he pointed me to this tutorial: https://www.phusionpassenger.com/library/deploy/nginx/deploy/ruby/#deploying-an-app-to-a-sub-uri following which I've changed in my `nginx.conf` section `location /tracks` to the following:

    location /tracks {
              passenger_base_uri /tracks;
              passenger_app_root /opt/tracks;
              passenger_document_root /opt/tracks/public;
              passenger_enabled on;
              alias   /opt/tracks/public;
              index  index.html index.htm;
          }
It solved the issue.
