### ISSUE TITLE
Precompile assets fails

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1954]
I'm running a very recent master (6492b1c3fe448ca408029eb2b507a2f94275dbae).

ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
rake, version 10.4.2

```
$ bundle exec rake assets:precompile RAILS_ENV=production
rake aborted!
Sass::SyntaxError: Undefined mixin 'make-xs-column'.
  (in /home/cotto/git/tracks/app/assets/stylesheets/login.css.scss:6)
/home/cotto/git/tracks/app/assets/stylesheets/login.css.scss:6:in `make-xs-column'
/home/cotto/git/tracks/app/assets/stylesheets/login.css.scss:6
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:253:in `visit_mixin'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/var/lib/gems/2.1.0/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/var/lib/gems/2.1.0/gems/sass-rails-4.0.4/lib/sass/rails/template.rb:22:in `evaluate'
/var/lib/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:197:in `block in evaluate'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `each'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/context.rb:194:in `evaluate'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `new'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:374:in `block in build_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:395:in `circular_call_protection'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:373:in `build_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:94:in `block in build_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:58:in `cache_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/bundled_asset.rb:37:in `init_with'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/asset.rb:24:in `from_hash'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/caching.rb:54:in `cache_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:93:in `build_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/base.rb:287:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/index.rb:61:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:211:in `block in find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:257:in `benchmark'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:210:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:119:in `block in compile'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `each'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/sprockets/manifest.rb:118:in `compile'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/2.1.0/gems/sprockets-2.11.3/lib/rake/sprocketstask.rb:146:in `with_logger'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by mattr-** [comment]
Ugh. I didn't catch this before because I hadn't deployed master to my local server until just now. Working on a fix.

**Comment by C-Otto** [comment]
:thumbsup:
