### ISSUE TITLE
uninitialized constant RenderingHelper::RedCloth

### ISSUE THREAD

**Issue by tinloaf** [TracksApp/tracks#2002]
Hi,

I just set up a Tracks installation from the current git master. I just added the first blocked todo (i.e. one depending on another todo). Also, this was the first time I tried to add notes to a todo item. When trying to add the todo item, I got a "Server Error". This is what popped up in the log:

```
  I, [2016-03-26T14:31:57.713356 #3814]  INFO -- : Read fragment views/todos/5-20160326133156740662000/20160326/todo/false/87f7861afa8c2849bbcddf7ac85b5c2d (0.2ms)
I, [2016-03-26T14:31:57.727423 #3814]  INFO -- : Read fragment views/todos/13-20160326133002546025000/successor/c25c0c196f66fda54f435e45bc9fe9eb (0.1ms)
I, [2016-03-26T14:31:57.727657 #3814]  INFO -- : Read fragment views/todos/14-20160326133157527154000/successor/c25c0c196f66fda54f435e45bc9fe9eb (0.1ms)
I, [2016-03-26T14:31:57.729644 #3814]  INFO -- : Write fragment views/todos/14-20160326133157527154000/successor/c25c0c196f66fda54f435e45bc9fe9eb (0.6ms)
I, [2016-03-26T14:31:57.729723 #3814]  INFO -- :   Rendered todos/_successor.html.erb (2.6ms)
I, [2016-03-26T14:31:57.730905 #3814]  INFO -- : Write fragment views/todos/5-20160326133156740662000/20160326/todo/false/87f7861afa8c2849bbcddf7ac85b5c2d (0.5ms)
I, [2016-03-26T14:31:57.730968 #3814]  INFO -- :   Rendered todos/_todo.html.erb (18.6ms)
I, [2016-03-26T14:31:57.731835 #3814]  INFO -- : Read fragment views/todos/14-20160326133157527154724/20160326/todo/false/87f7861afa8c2849bbcddf7ac85b5c2d (0.1ms)
I, [2016-03-26T14:31:57.736745 #3814]  INFO -- :   Rendered todos/_todo.html.erb (5.2ms)
I, [2016-03-26T14:31:57.736815 #3814]  INFO -- :   Rendered todos/create.js.erb (27.8ms)
I, [2016-03-26T14:31:57.736937 #3814]  INFO -- : Completed 500 Internal Server Error in 1010ms (ActiveRecord: 937.0ms)
F, [2016-03-26T14:31:57.738471 #3814] FATAL -- : 
ActionView::Template::Error (uninitialized constant RenderingHelper::RedCloth):
    38:         <%= image_tag_for_recurring_todo(todo) if todo.from_recurring_todo? %>
    39:         <%= tag_list(todo) %>
    40:         <%= deferred_due_date(todo) %>
    41:         <%= project_and_context_links( todo, parent_container_type, :suppress_context => suppress_context, :suppress_project => suppress_project ) %>
    42:         <%= collapsed_notes_image(todo) if todo.notes.present? %>
    43:         <%= collapsed_successors_image(todo) if todo.has_pending_successors %>
    44:         <%= attachment_image(todo) if todo.attachments.present? %>
  app/helpers/rendering_helper.rb:39:in `textile'
  app/helpers/rendering_helper.rb:23:in `render_text'
  app/helpers/todos_helper.rb:223:in `block in collapsed_notes_image'
  app/helpers/todos_helper.rb:220:in `collapsed_notes_image'
  app/views/todos/_todo.html.erb:41:in `block in _app_views_todos__todo_html_erb__4151886524301036631_29889760'
  app/views/todos/_todo.html.erb:13:in `_app_views_todos__todo_html_erb__4151886524301036631_29889760'
  app/helpers/application_helper.rb:251:in `js_render'
  app/views/todos/create.js.erb:85:in `_app_views_todos_create_js_erb___321015244467879063_42056540'
  app/controllers/todos_controller.rb:145:in `block (2 levels) in create'
  app/controllers/todos_controller.rb:114:in `create'
```

When I removed the notes, I could successfully add the todo, **but**: Now I can't access the tickler page (by the way: it's called "Notizbuch" in German, which is weird.. that would translate to "Notebook" and is kind of a weird translation for "tickler"?) I'm getting a 500 error, and this is what my log shows:

```
I, [2016-03-26T14:32:47.618651 #3814]  INFO -- : Started GET "/tickler" for 188.100.79.8 at 2016-03-26 14:32:47 +0100
I, [2016-03-26T14:32:47.620194 #3814]  INFO -- : Processing by TodosController#list_deferred as HTML
I, [2016-03-26T14:32:47.657154 #3814]  INFO -- : Read fragment views/contexts/1-20160326133218474377000/deferred/20160326//e965f7777543518cc6376748df483765 (0.1ms)
I, [2016-03-26T14:32:47.658518 #3814]  INFO -- : Read fragment views/todos/15-20160326133206854023000/20160326/deferred/false/87f7861afa8c2849bbcddf7ac85b5c2d (0.0ms)
I, [2016-03-26T14:32:47.662834 #3814]  INFO -- :   Rendered todos/_todo.html.erb (4.7ms)
I, [2016-03-26T14:32:47.662904 #3814]  INFO -- :   Rendered todos/_collection.html.erb (5.4ms)
I, [2016-03-26T14:32:47.662961 #3814]  INFO -- :   Rendered contexts/_context.html.erb (6.2ms)
I, [2016-03-26T14:32:47.663026 #3814]  INFO -- :   Rendered todos/list_deferred.html.erb within layouts/application (7.4ms)
I, [2016-03-26T14:32:47.663162 #3814]  INFO -- : Completed 500 Internal Server Error in 43ms (ActiveRecord: 3.3ms)
F, [2016-03-26T14:32:47.665204 #3814] FATAL -- : 
ActionView::Template::Error (uninitialized constant RenderingHelper::RedCloth):
    38:         <%= image_tag_for_recurring_todo(todo) if todo.from_recurring_todo? %>
    39:         <%= tag_list(todo) %>
    40:         <%= deferred_due_date(todo) %>
    41:         <%= project_and_context_links( todo, parent_container_type, :suppress_context => suppress_context, :suppress_project => suppress_project ) %>
    42:         <%= collapsed_notes_image(todo) if todo.notes.present? %>
    43:         <%= collapsed_successors_image(todo) if todo.has_pending_successors %>
    44:         <%= attachment_image(todo) if todo.attachments.present? %>
  app/helpers/rendering_helper.rb:39:in `textile'
  app/helpers/rendering_helper.rb:23:in `render_text'
  app/helpers/todos_helper.rb:223:in `block in collapsed_notes_image'
  app/helpers/todos_helper.rb:220:in `collapsed_notes_image'
  app/views/todos/_todo.html.erb:41:in `block in _app_views_todos__todo_html_erb__4151886524301036631_42331360'
  app/views/todos/_todo.html.erb:13:in `_app_views_todos__todo_html_erb__4151886524301036631_42331360'
  app/helpers/todos_helper.rb:131:in `block in todos_container_items'
  app/helpers/todos_helper.rb:129:in `todos_container_items'
  app/views/todos/_collection.html.erb:6:in `block in _app_views_todos__collection_html_erb__452700888233224952_31030780'
  app/helpers/todos_helper.rb:108:in `block in todos_container'
  app/helpers/todos_helper.rb:104:in `todos_container'
  app/views/todos/_collection.html.erb:4:in `_app_views_todos__collection_html_erb__452700888233224952_31030780'
  app/views/contexts/_context.html.erb:8:in `block in _app_views_contexts__context_html_erb__3768497164767611344_35889260'
  app/views/contexts/_context.html.erb:5:in `_app_views_contexts__context_html_erb__3768497164767611344_35889260'
  app/helpers/todos_helper.rb:26:in `show_grouped_todos'
  app/views/todos/list_deferred.html.erb:5:in `_app_views_todos_list_deferred_html_erb___1630582432668511446_40010520'
```

**Comment by mattr-** [comment]
Thanks for reporting this issue. I highly recommend that you not use git master for a production installation and use the 2.3 release series instead. We'll take a look at this and get it resolved before the next major release.

**Comment by tinloaf** [comment]
Well, "production". ;) It's my personal ToDo-List and hidden behind HTTP auth. If it fails, I can handle it, and I like to help with OSS development. So please let me know if I can help debugging this.

**Comment by tinloaf** [comment]
Some further debugging revealed some more information:

- It's definitely the fact that a note is attached to a ToDo that is causing the troubles. Even a note "a" is making trouble, so it's not some weird characters
- The mobile view works
- Adding ToDos with notes actually worked (although it says "server error" as described above) - the Todo is created
