### ISSUE TITLE
Error when adding multiple todos

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2048]
I'm running 1ba829e9607b2622c2a5dc8177111f66c290d813 with the commits from PR #2045 (which seems unrelated).

I just added several todos using the "Multiple next actions (one on each line)" feature. This triggered an error message in the UI, with this in the logs:

```
I, [2016-12-19T22:45:35.760453 #4363]  INFO -- :   Rendered todos/create_multiple.js.erb (2.5ms)
I, [2016-12-19T22:45:35.760721 #4363]  INFO -- : Completed 500 Internal Server Error in 302ms (ActiveRecord: 112.8ms)
F, [2016-12-19T22:45:35.762495 #4363] FATAL -- : 
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    19:   hide_empty_message();
    20:   TracksPages.hide_errors();
    21:   TracksPages.set_page_badge(<%= @down_count %>);
    22:   <% if should_show_new_item -%>
    23:     <% if @new_context_created -%>
    24:       insert_new_context_with_new_todo();
    25:     <% else -%>
  app/helpers/todos_helper.rb:449:in `show_todo_on_current_project_page'
  app/helpers/todos_helper.rb:459:in `block (2 levels) in should_show_new_item'
  lib/tracks/source_view.rb:21:in `method_missing'
  app/helpers/todos_helper.rb:459:in `block in should_show_new_item'
  lib/tracks/source_view.rb:43:in `source_view'
  app/helpers/todos_helper.rb:454:in `should_show_new_item'
  app/views/todos/create_multiple.js.erb:22:in `_app_views_todos_create_multiple_js_erb___2240206101933784841_69904538323460'
  app/controllers/todos_controller.rb:223:in `block (2 levels) in create_multiple'
  app/controllers/todos_controller.rb:200:in `create_multiple'
  app/controllers/todos_controller.rb:88:in `create'
```

**Comment by C-Otto** [comment]
Ah, I found the ones I tried to add - in another project :)

1) Create project
2) Fix name of project by clicking on name in project view
3) Add multiple todos without reloading the page
4) Crash
