### ISSUE TITLE
Mysql error : specified key was too long

### ISSUE THREAD

**Issue by sezio** [TracksApp/tracks#2119]
Hello,

I tried to install tracks on my personal server (debian9 with MariaDB) but I get the error below when the schema gets installed. 
Can you tell me if you already saw that error ? What should I do ? 

```
/opt/tracks$ bundle exec rake db:migrate RAILS_ENV=production
Rails Error: Unable to access log file. Please ensure that /opt/tracks/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/tracks/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
   (96.4ms)  CREATE TABLE `schema_migrations` (`version` varchar(191) NOT NULL) ENGINE=InnoDB
   (67.0ms)  CREATE UNIQUE INDEX `unique_schema_migrations`  ON `schema_migrations` (`version`) 
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Migrating to CreateTracksDb (1)
== 1 CreateTracksDb: migrating ================================================
-- create_table(:contexts)
   (37.7ms)  CREATE TABLE `contexts` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255) NOT NULL, `position` int(11) NOT NULL, `hide` tinyint(1) DEFAULT 0) ENGINE=InnoDB
   -> 0.0401s
-- create_table(:projects)
   (43.8ms)  CREATE TABLE `projects` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255) NOT NULL, `position` int(11) NOT NULL, `done` tinyint(1) DEFAULT 0) ENGINE=InnoDB
   -> 0.0456s
-- create_table(:todos)
   (26.7ms)  CREATE TABLE `todos` (`id` int(11) auto_increment PRIMARY KEY, `context_id` int(11) NOT NULL, `project_id` int(11), `description` varchar(255) NOT NULL, `notes` text, `done` tinyint(1) DEFAULT 0 NOT NULL, `created` datetime, `due` date, `completed` datetime) ENGINE=InnoDB
   -> 0.0276s
-- create_table(:users)
   (85.7ms)  CREATE TABLE `users` (`id` int(11) auto_increment PRIMARY KEY, `login` varchar(80) NOT NULL, `password` varchar(40) NOT NULL, `word` varchar(255), `is_admin` tinyint(1) DEFAULT 0 NOT NULL) ENGINE=InnoDB
   -> 0.0870s
== 1 CreateTracksDb: migrated (0.2014s) =======================================

   (0.3ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('1')
   (2.8ms)  COMMIT
Migrating to AddUserId (2)
== 2 AddUserId: migrating =====================================================
-- add_column(:contexts, :user_id, :integer, {:default=>1})
   (61.5ms)  ALTER TABLE `contexts` ADD `user_id` int(11) DEFAULT 1
   -> 0.0619s
-- add_column(:projects, :user_id, :integer, {:default=>1})
   (96.5ms)  ALTER TABLE `projects` ADD `user_id` int(11) DEFAULT 1
   -> 0.0974s
-- add_column(:todos, :user_id, :integer, {:default=>1})
   (73.1ms)  ALTER TABLE `todos` ADD `user_id` int(11) DEFAULT 1
   -> 0.0734s
  AddUserId::Context Load (0.5ms)  SELECT `contexts`.* FROM `contexts`
  AddUserId::Project Load (0.3ms)  SELECT `projects`.* FROM `projects`
  AddUserId::Todo Load (0.3ms)  SELECT `todos`.* FROM `todos`
== 2 AddUserId: migrated (0.2408s) ============================================

   (0.1ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('2')
   (3.6ms)  COMMIT
Migrating to CreatedAt (3)
== 3 CreatedAt: migrating =====================================================
-- rename_column(:todos, "created", "created_at")
   (4.7ms)  ALTER TABLE `todos` CHANGE `created` `created_at` datetime DEFAULT NULL
   -> 0.0075s
== 3 CreatedAt: migrated (0.0078s) ============================================

   (0.1ms)  BEGIN
  SQL (0.2ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('3')
   (11.9ms)  COMMIT
Migrating to Notes (4)
== 4 Notes: migrating =========================================================
-- create_table(:notes)
   (42.9ms)  CREATE TABLE `notes` (`id` int(11) auto_increment PRIMARY KEY, `user_id` int(11) NOT NULL, `project_id` int(11) NOT NULL, `body` text, `created_at` datetime, `updated_at` datetime) ENGINE=InnoDB
   -> 0.0436s
== 4 Notes: migrated (0.0437s) ================================================

   (0.3ms)  BEGIN
  SQL (0.3ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('4')
   (2.5ms)  COMMIT
Migrating to AddProjectDescription (5)
== 5 AddProjectDescription: migrating =========================================
-- add_column(:projects, :description, :text)
   (70.2ms)  ALTER TABLE `projects` ADD `description` text
   -> 0.0707s
== 5 AddProjectDescription: migrated (0.0710s) ================================

   (0.5ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('5')
   (13.0ms)  COMMIT
Migrating to AddPreferencesToUserTable (6)
== 6 AddPreferencesToUserTable: migrating =====================================
-- add_column(:users, :preferences, :text)
   (87.4ms)  ALTER TABLE `users` ADD `preferences` text
   -> 0.0880s
  AddPreferencesToUserTable::User Load (0.3ms)  SELECT `users`.* FROM `users`
== 6 AddPreferencesToUserTable: migrated (0.0911s) ============================

   (0.1ms)  BEGIN
  SQL (1.6ms)  INSERT INTO `schema_migrations` (`version`) VALUES ('6')
   (4.6ms)  COMMIT
Migrating to AddSessionsTable (7)
== 7 AddSessionsTable: migrating ==============================================
-- create_table(:sessions)
   (38.2ms)  CREATE TABLE `sessions` (`id` int(11) auto_increment PRIMARY KEY, `session_id` varchar(255), `data` text, `updated_at` datetime) ENGINE=InnoDB
   -> 0.0390s
-- add_index(:sessions, :session_id)
   (1.5ms)  CREATE  INDEX `index_sessions_on_session_id`  ON `sessions` (`session_id`) 
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE  INDEX `index_sessions_on_session_id`  ON `sessions` (`session_id`) 
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:549:in `add_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:416:in `method_missing'
/opt/tracks/db/migrate/007_add_sessions_table.rb:9:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:571:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:611:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE  INDEX `index_sessions_on_session_id`  ON `sessions` (`session_id`) 
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:549:in `add_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:416:in `method_missing'
/opt/tracks/db/migrate/007_add_sessions_table.rb:9:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:571:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:611:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `_query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:80:in `block in query'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `handle_interrupt'
/var/lib/gems/2.3.0/gems/mysql2-0.3.21/lib/mysql2/client.rb:79:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:549:in `add_index'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:665:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:416:in `method_missing'
/opt/tracks/db/migrate/007_add_sessions_table.rb:9:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:571:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:611:in `exec_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:591:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:590:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:768:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1071:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:984:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:980:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

I saw on stackoverflow that the "Specified key was too long; max key length is 767" is a mysql error that can be solved by setting the database in myisam instead of innodb. 
Can somebdoy tell me how to do this ? I'm a complete noob to Ruby on Rails and I did not even found the file where the database schema comes from using a grep 

Also, I have other databases on my sql server and they are all configured as : 
CHARSET=utf8 COLLATE=utf8_bin 

tracks table that can be created are all 
CHARSET=utf8mb4

Is that the issue ? How could I fix it ? 

Thanks ! 

Sebastien

**Comment by mattr-** [comment]
I've seen this before with other things. What version of MariaDB is your server running?

**Comment by mattr-** [comment]
Rather than running `bin/rake db:migrate` can you run `bin/rake db:schema:load`? Migrations are really only necessary after the initial schema load, which is what `bin/rake db:schema:load` does.

**Comment by mattr-** [comment]
If `bin/rake db:schema:load` doesn't work - and i suspect that it won't - is there a backports package that you could install for MariaDB 10.2?

**Comment by sezio** [comment]
It looks like the bin/rake db:schema:load needs docker-compose : 

```
/opt/tracks$ bin/rake db:schema:load
/opt/tracks/bin/../script/docker-environment: 17: exec: docker-compose: not found
```

I could install it but I don't see the point of using docker-compose in that case ? Am I doing something wrong ? 

If there's no other solution than upgrading to maria db 10.2, I'll probably do it later. I thought there would be an easy solution and I hoped that I was not the only one in that case...
I'll update the issue when I'll have upgraded mariadb to let you know if everything's fine with a more recent version

**Comment by mattr-** [comment]
Rather than pulling master, could you use a released version please? You shouldn't have these issues with the latest release.

**Comment by sezio** [comment]
Yep, I just downloaded the 2.3.0 version and  : 
* `bundle install --without development,test`
* configured the config/database.yml 
* copied the site.yml.tmpl to site.yml 
* played `bundle exec rake db:migrate RAILS_ENV=production` from the document root and I get the exact same error 
* I tried again and typed in the command you gave me `bin/rake db:schema:load RAILS_ENV=production` and I get the same error on an other key : 

```
/opt/tracks-2.3.0/tracks-2.3.0$ bin/rake db:schema:load RAILS_ENV=production
Warning: Running `gem pristine --all` to regenerate your installed gemspecs (and deleting then reinstalling your bundle if you use bundle --path) will improve the startup performance of Spring.
/var/lib/gems/2.3.0/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466
/opt/tracks-2.3.0/tracks-2.3.0/app/models/recurring_todos/abstract_recurring_todos_builder.rb:80: warning: key :target is duplicated and overwritten on line 85
-- create_table("contexts", {:force=>true})
   -> 0.0737s
-- add_index("contexts", ["user_id", "name"], {:name=>"index_contexts_on_user_id_and_name", :using=>:btree})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE  INDEX `index_contexts_on_user_id_and_name` USING btree ON `contexts` (`user_id`, `name`) 
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:525:in `add_index'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:656:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:628:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:628:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:648:in `method_missing'
/opt/tracks-2.3.0/tracks-2.3.0/db/schema.rb:25:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:42:in `instance_eval'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:42:in `define'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:62:in `define'
/opt/tracks-2.3.0/tracks-2.3.0/db/schema.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:171:in `load_schema_for'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:183:in `block in load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:223:in `block in each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:222:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:222:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:182:in `load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
-e:1:in `<main>'
Mysql2::Error: Specified key was too long; max key length is 767 bytes
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `query'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `block in execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:303:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/mysql2_adapter.rb:228:in `execute'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:525:in `add_index'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:656:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:628:in `block in say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:628:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/migration.rb:648:in `method_missing'
/opt/tracks-2.3.0/tracks-2.3.0/db/schema.rb:25:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:42:in `instance_eval'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:42:in `define'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/schema.rb:62:in `define'
/opt/tracks-2.3.0/tracks-2.3.0/db/schema.rb:14:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:171:in `load_schema_for'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:183:in `block in load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:223:in `block in each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:222:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:222:in `each_current_configuration'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/tasks/database_tasks.rb:182:in `load_schema_current'
/var/lib/gems/2.3.0/gems/activerecord-4.1.11/lib/active_record/railties/databases.rake:238:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `block in load'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:232:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:241:in `load'
-e:1:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)
```

**Comment by sezio** [comment]
I finally decided to use sqlite and it is working fine with it. 
I do not know if this is an issue you want to work on or not so I'll let it open but feel free to close it if you don't estimate it is necessary to work on this issue as using mariadb 10.2 should solve the problem (I did not tried)

Thanks @mattr- for taking the time to help me!

Have a nice day

**Comment by mattr-** [comment]
:wave: Hi! I'm going to go ahead and close this, as using MySQL 5.7/MariaDB 10.2 is definitely the preferred solution if you're going with MySQL. Thanks so much for taking the time to report this and work with me on a solution! :heart:

**Comment by sezio** [comment]
Of course, you can close it. 
Thanks for taking the time to try to find a solution!
