### ISSUE TITLE
Missing constant when rendering recurring todos

### ISSUE THREAD

**Issue by mattr-** [TracksApp/tracks#2142]
From the mailing list:

```
I, [2018-11-12T18:25:08.715834 #17778]  INFO -- : [6705ff5a-0465-468d-a723-1fed694a4a01] Rendered collection of todos/_todo.html.erb [15 times] (95.4ms)
I, [2018-11-12T18:25:08.716138 #17778]  INFO -- : [6705ff5a-0465-468d-a723-1fed694a4a01]   Rendered todos/_collection.html.erb (97.0ms)
I, [2018-11-12T18:25:08.716232 #17778]  INFO -- : [6705ff5a-0465-468d-a723-1fed694a4a01]   Rendered collection of contexts/_context.html.erb [12 times] (178.1ms)
I, [2018-11-12T18:25:08.716338 #17778]  INFO -- : [6705ff5a-0465-468d-a723-1fed694a4a01]   Rendered todos/index.html.erb within layouts/application (200.5ms)
I, [2018-11-12T18:25:08.717180 #17778]  INFO -- : [6705ff5a-0465-468d-a723-1fed694a4a01] Completed 500 Internal Server Error in 1271ms (ActiveRecord: 103.9ms)
F, [2018-11-12T18:25:08.720415 #17778] FATAL -- : [6705ff5a-0465-468d-a723-1fed694a4a01] F, [2018-11-12T18:25:08.720486 #17778] FATAL -- :
[6705ff5a-0465-468d-a723-1fed694a4a01] ActionView::Template::Error (uninitialized constant Tracks::AttributeHandler): F, [2018-11-12T18:25:08.721192 #17778] FATAL -- :
[6705ff5a-0465-468d-a723-1fed694a4a01]     34:       <%= grip_span(todo) %>
[6705ff5a-0465-468d-a723-1fed694a4a01]     35:       <div class="description<%= staleness_class( todo ) %>">
[6705ff5a-0465-468d-a723-1fed694a4a01]     36:         <%= date_span(todo) -%>
[6705ff5a-0465-468d-a723-1fed694a4a01]     37:         <span class="todo.descr"><%= h todo.description %></span>
[6705ff5a-0465-468d-a723-1fed694a4a01]     38:         <%= image_tag_for_recurring_todo(todo) if todo.from_recurring_todo? %>
[6705ff5a-0465-468d-a723-1fed694a4a01]     39:         <%= tag_list(todo) %>
[6705ff5a-0465-468d-a723-1fed694a4a01]     40:         <%= deferred_due_date(todo) %>
F, [2018-11-12T18:25:08.721280 #17778] FATAL -- : [6705ff5a-0465-468d-a723-1fed694a4a01]
F, [2018-11-12T18:25:08.721338 #17778] FATAL -- : [6705ff5a-0465-468d-a723-1fed694a4a01] app/models/recurring_todos/abstract_recurrence_pattern.rb:73:in `build_from_recurring_todo'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/models/recurring_todo.rb:76:in `pattern'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/models/recurring_todo.rb:86:in `recurring_target_as_text'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/application_helper.rb:106:in `recurrence_pattern_as_text'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:242:in `image_tag_for_recurring_todo'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/todos/_todo.html.erb:37:in `block in _app_views_todos__todo_html_erb___841895864072784174_70308153675240'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/todos/_todo.html.erb:13:in `_app_views_todos__todo_html_erb___841895864072784174_70308153675240'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:133:in `block in todos_container_items'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:131:in `todos_container_items'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/todos/_collection.html.erb:6:in `block in _app_views_todos__collection_html_erb__465889732732105804_70308153627820'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:110:in `block in todos_container'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:106:in `todos_container'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/todos/_collection.html.erb:4:in `_app_views_todos__collection_html_erb__465889732732105804_70308153627820'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/contexts/_context.html.erb:8:in `block in _app_views_contexts__context_html_erb___3946485166821518221_70308153519040'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/contexts/_context.html.erb:5:in `_app_views_contexts__context_html_erb___3946485166821518221_70308153519040'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/helpers/todos_helper.rb:28:in `show_grouped_todos'
[6705ff5a-0465-468d-a723-1fed694a4a01] app/views/todos/index.html.erb:4:in `_app_views_todos_index_html_erb___1216311748849686157_70308153291940'
```

cc: @C-Otto as the person reporting this on the mailing list.

**Comment by C-Otto** [comment]
Yes, that helped. Thank you a lot!
