### ISSUE TITLE
Migration not working properly in MySQL

### ISSUE THREAD

**Issue by ZeiP** [TracksApp/tracks#2295]
I tried to upgrade my production instance now to 2.4.0. The migration now fails on (my) MySQL, because the keys were changed:

```
www-tracks@greenore:/srv/ror/tracks$ bundle exec rake db:migrate RAILS_ENV=production
== 20190618202817 AddUserIdToTag: migrating ===================================
-- add_column(:tags, :user_id, :integer)
   -> 0.0075s
-- execute("      SELECT t.id AS tid, tds.user_id AS todo_uid, rt.user_id AS rtodo_uid\n      FROM tags t\n      JOIN taggings tgs ON tgs.tag_id = t.id\n      LEFT OUTER JOIN todos tds\n       ON tgs.taggable_type = 'Todo' AND tds.id = tgs.taggable_id\n      LEFT OUTER JOIN recurring_todos rt\n       ON tgs.taggable_type = 'RecurringTodo' AND rt.id = tgs.taggable_id\n      WHERE rt.id IS NOT NULL OR tds.id IS NOT NULL\n      GROUP BY t.id, tds.user_id, rt.user_id\n")
   -> 0.0060s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

no implicit conversion of String into Integer
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:22:in `[]'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:22:in `block in up'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:21:in `each'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:21:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:777:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

Caused by:
TypeError: no implicit conversion of String into Integer
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:22:in `[]'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:22:in `block in up'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:21:in `each'
/srv/ror/tracks/db/migrate/20190618202817_add_user_id_to_tag.rb:21:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:777:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:817:in `exec_migration'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:797:in `block in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:796:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:977:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1345:in `ddl_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `each'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `block in migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1210:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1036:in `up'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:1011:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/srv/ror/tracks/vendor/bundle/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

I checked what the row contains, and it's just an array of values. @mattr-, I'm wondering why it worked when you tested the PR #2278 – any ideas? Anyway it seems we need to refactor the migration code to fix both the PostgreSQL and MySQL environments.

**Comment by mattr-** [comment]
Should be fixed by #2296
