### ISSUE TITLE
DB migration error on install

### ISSUE THREAD

**Issue by m-angelov** [TracksApp/tracks#2331]
I'm trying to install Tracks, but I get warnings and errors when I run the migrations. I get the same behaviour with Rails 2.7 on Ubuntu and Arch Linux, using the master git branch.

```
bundle exec rake db:migrate RAILS_ENV=production --trace
```
```
/usr/lib/ruby/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_1' is reserved for numbered parameter; consider another name
/usr/lib/ruby/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_2' is reserved for numbered parameter; consider another name                          
/usr/lib/ruby/gems/2.7.0/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_3' is reserved for numbered parameter; consider another name                          
** Invoke db:migrate (first_time)                                                                                                                                          
** Invoke db:load_config (first_time)                                                                                                                                      
** Invoke environment (first_time)                                                                                                                                         
** Execute environment                                                                                                                                                     
/var/www/tracks/config/initializers/sanitizer.rb:1: warning: constant Loofah::HTML5::WhiteList is deprecated                                                               
** Execute db:load_config                                                                                                                                                  
** Execute db:migrate                                                                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/sqlite3/schema_statements.rb:60: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:263: warning: The called method `initialize' is defined here                                                                                                                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/schema_migration.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:231: warning: The called method `string' is defined here                                                                                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:366: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:415: warning: The called method `new_column_definition' is defined here                                                                                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_creation.rb:19: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1066: warning: The called method `type_to_sql' is defined here                                                                                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/internal_metadata.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:231: warning: The called method `string' is defined here                                                                                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:260: warning: The called method `transaction' is defined here                                                                                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:171: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:97: warning: The called method `initialize' is defined here                                                                                                                                                                          
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:301: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:204: warning: The called method `primary_key' is defined here                                                                                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:468: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_definitions.rb:415: warning: The called method `new_column_definition' is defined here                                                                                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.1/lib/active_model/type/integer.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/activemodel-5.2.4.1/lib/active_model/type/value.rb:8: warning: The called method `initialize' is defined here                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:427: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:290: warning: The called method `create_table' is defined here                                                                                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:764: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1135: warning: The called method `add_index_options' is defined here                                                                                                                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1162: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1215: warning: The called method `quoted_columns_for_index' is defined here                                                                                                                                                    
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1219: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1207: warning: The called method `add_options_for_index_columns' is defined here                                                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1209: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:1190: warning: The called method `add_index_sort_order' is defined here                                                                                                                                                        
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:871: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                                                                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:290: warning: The called method `create_table' is defined here   
```
```
== 30 SetNilTimestamps: migrated (0.0094s) ====================================rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:                                                                                              

undefined method `new_ostruct_member' for #<OpenStruct column=:state>                                                                                                      
Did you mean?  new_ostruct_member!                                                                                                                                         
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/base.rb:91:in `configure'                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/base.rb:11:in `initialize'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/aasm.rb:24:in `new'                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/aasm.rb:24:in `aasm'                                                                                                     
/var/www/tracks/app/models/todo.rb:75:in `<class:Todo>'                                                                                                                    
/var/www/tracks/app/models/todo.rb:1:in `<top (required)>'                                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'                                                                    
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'                                                            
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'                                                                    
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'                                                   
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'                                                     
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'                                                  
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'                                                        
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:13:in `loading'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:37:in `load_interlock'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:356:in `require_or_load'                                                            
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:510:in `load_missing_constant'                                                      
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:195:in `const_missing'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:542:in `load_missing_constant'                                                      
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:195:in `const_missing'                                                              
/var/www/tracks/db/migrate/046_fix_incorrectly_hidden_todos.rb:4:in `up'                                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:777:in `up'                                                                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:817:in `exec_migration'                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'                                                     
/usr/lib/ruby/2.7.0/benchmark.rb:293:in `measure'                                                                                                                          
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:797:in `block in migrate'                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:796:in `migrate'                                                                         
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:977:in `migrate'                                                                         
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'                                                       
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'                     
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212:in `transaction'                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1343:in `ddl_transaction'                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `each'                                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1212:in `migrate'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1036:in `up'                                                                             
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1011:in `migrate'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'                                  
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'                                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'                                                                   
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'                                                                              
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'                                                                                
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'                                                                                              
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'                                                                                                
/usr/sbin/rake:23:in `load'                                                                                                                                                
/usr/sbin/rake:23:in `<top (required)>'                                                                                                                                    
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'                                                                                           
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'                                                                                    
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'                                                         
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'                                                                          
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'                                                                   
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'                                                                                            
/usr/sbin/bundle:23:in `load'                                                                                                                                              
/usr/sbin/bundle:23:in `<main>'                                                                                                                                            

Caused by:                                                                                                                                                                 
NoMethodError: undefined method `new_ostruct_member' for #<OpenStruct column=:state>                                                                                       
Did you mean?  new_ostruct_member!                                                                                                                                         
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/base.rb:91:in `configure'                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/base.rb:11:in `initialize'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/aasm.rb:24:in `new'                                                                                                      
/usr/lib/ruby/gems/2.7.0/gems/aasm-3.4.0/lib/aasm/aasm.rb:24:in `aasm'                                                                                                     
/var/www/tracks/app/models/todo.rb:75:in `<class:Todo>'                                                                                                                    
/var/www/tracks/app/models/todo.rb:1:in `<top (required)>'                                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'                                                                    
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'                                                            
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'                                                                    
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:378:in `block in require_or_load'                                                   
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'                                                     
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'                                                  
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'                                                        
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies/interlock.rb:13:in `loading'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:37:in `load_interlock'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:356:in `require_or_load'                                                            
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:510:in `load_missing_constant'                                                      
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:195:in `const_missing'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:542:in `load_missing_constant'                                                      
/usr/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:195:in `const_missing'                                                              
/var/www/tracks/db/migrate/046_fix_incorrectly_hidden_todos.rb:4:in `up'                                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:777:in `up'                                                                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:817:in `exec_migration'                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'                                                     
/usr/lib/ruby/2.7.0/benchmark.rb:293:in `measure'                                                                                                                          
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:797:in `block in migrate'                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:796:in `migrate'                                                                         
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:977:in `migrate'                                                                         
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'                                                       
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'                     
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `synchronize'                                      
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/transactions.rb:212:in `transaction'                                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1343:in `ddl_transaction'                                                                
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'                                               
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'                                                  
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `each'                                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'                                                           
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1212:in `migrate'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1036:in `up'                                                                             
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/migration.rb:1011:in `migrate'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'                                                              
/usr/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'                                  
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'                                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'                                                                                                
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'                                                                                                 
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'                                                                   
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'                                                                              
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'                                                                                
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'                                                                                       
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'                                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'                                                                     
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'                                                                                              
/usr/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'                                                                                                
/usr/sbin/rake:23:in `load'                                                                                                                                                
/usr/sbin/rake:23:in `<top (required)>'                                                                                                                                    
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'                                                                                           
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'                                                                                    
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'                                                         
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'                                                                          
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'                                                                                            
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'                                                                        
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'                                                                                               
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'                                                                                   
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'                                                                   
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'                                                                                            
/usr/sbin/bundle:23:in `load'                                                                                                                                              
/usr/sbin/bundle:23:in `<main>'                                                                                                                                            
Tasks: TOP => db:migrate
```

Can somebody point me to some way to resolve this?

Thanks!

**Comment by mattr-** [comment]
Tracks has not been tested with Ruby 2.7. Your best bet is use ruby 2.6 instead.

**Comment by m-angelov** [comment]
I've added a small PR to update the documentation regarding this: https://github.com/TracksApp/tracks/pull/2339#issue-371066998
