### ISSUE TITLE
Adding actions from the Context page gives a server error

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2471]
As title. To reproduce, create a context, go to the page e.g. "/contexts/1" and then add a new action. The "server error" red box will display in top-right, but the action *is* added. However, the context view does not refresh to show it - you have to go back to the main page to see the new task. 

Server logs suggest it's a problem in the todos controller:

```
I, [2020-09-01T12:31:11.474228 #1]  INFO -- : [3802360c-03c0-411d-b100-9af886a64112] Started POST "/todos" for 172.20.10.155 at 2020-09-01 12:31:11 +0000
I, [2020-09-01T12:31:11.475196 #1]  INFO -- : [3802360c-03c0-411d-b100-9af886a64112] Processing by TodosController#create as JS
I, [2020-09-01T12:31:11.475328 #1]  INFO -- : [3802360c-03c0-411d-b100-9af886a64112]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[redacted]", "default_project_name"=>"", "default_context_name"=>"work", "new_todo_starred"=>"false", "todo"=>{"description"=>"test", "notes"=>"", "due"=>"", "show_from"=>""}, "project_name"=>"", "context_name"=>"work", "initial_tag_list"=>"", "tag_list"=>"", "predecessor_input"=>"", "predecessor_list"=>"", "_source_view"=>"context", "_group_view_by"=>"context", "_tag_name"=>""}
D, [2020-09-01T12:31:11.477602 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.479503 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Preference Load (0.5ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.482684 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Context Load (0.8ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."user_id" = $1 AND "contexts"."name" = $2 ORDER BY position ASC LIMIT $3  [["user_id", 1], ["name", "work"], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.484543 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   CACHE Context Load (0.0ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."user_id" = $1 AND "contexts"."name" = $2 ORDER BY position ASC LIMIT $3  [["user_id", 1], ["name", "work"], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.486746 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.488277 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Tag Load (0.7ms)  SELECT "tags".* FROM "tags" WHERE "tags"."user_id" = $1  [["user_id", 1]]
D, [2020-09-01T12:31:11.492017 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]    (0.5ms)  BEGIN
D, [2020-09-01T12:31:11.492990 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Context Load (0.7ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2020-09-01T12:31:11.500466 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Todo Create (0.9ms)  INSERT INTO "todos" ("context_id", "description", "notes", "created_at", "state", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["context_id", 1], ["description", "test"], ["notes", ""], ["created_at", "2020-09-01 12:31:11.493633"], ["state", "active"], ["updated_at", "2020-09-01 12:31:11.493633"]]
D, [2020-09-01T12:31:11.504478 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Todo Load (0.8ms)  SELECT "todos".* FROM "todos" INNER JOIN "dependencies" ON "todos"."id" = "dependencies"."predecessor_id" WHERE "dependencies"."successor_id" = $1  [["successor_id", 34]]
D, [2020-09-01T12:31:11.506336 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Context Update (0.8ms)  UPDATE "contexts" SET "updated_at" = $1 WHERE "contexts"."id" = $2  [["updated_at", "2020-09-01 12:31:11.501043"], ["id", 1]]
D, [2020-09-01T12:31:11.523572 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]    (16.9ms)  COMMIT
D, [2020-09-01T12:31:11.526528 #1] DEBUG -- : [3802360c-03c0-411d-b100-9af886a64112]   Todo Exists? (0.9ms)  SELECT 1 AS one FROM "todos" INNER JOIN "dependencies" ON "todos"."id" = "dependencies"."predecessor_id" WHERE "dependencies"."successor_id" = $1 AND (NOT (todos.state = 'completed')) LIMIT $2  [["successor_id", 34], ["LIMIT", 1]]
I, [2020-09-01T12:31:11.529301 #1]  INFO -- : [3802360c-03c0-411d-b100-9af886a64112] Completed 500 Internal Server Error in 54ms (ActiveRecord: 24.1ms | Allocations: 7584)
F, [2020-09-01T12:31:11.530145 #1] FATAL -- : [3802360c-03c0-411d-b100-9af886a64112]   
[3802360c-03c0-411d-b100-9af886a64112] NoMethodError (undefined method `context_id' for nil:NilClass):
[3802360c-03c0-411d-b100-9af886a64112]   
[3802360c-03c0-411d-b100-9af886a64112] app/controllers/todos_controller.rb:943:in `block (2 levels) in determine_down_count'
[3802360c-03c0-411d-b100-9af886a64112] lib/tracks/source_view.rb:17:in `context'
[3802360c-03c0-411d-b100-9af886a64112] app/controllers/todos_controller.rb:942:in `block in determine_down_count'
[3802360c-03c0-411d-b100-9af886a64112] lib/tracks/source_view.rb:43:in `source_view'
[3802360c-03c0-411d-b100-9af886a64112] app/controllers/todos_controller.rb:938:in `determine_down_count'
[3802360c-03c0-411d-b100-9af886a64112] app/controllers/todos_controller.rb:137:in `block (2 levels) in create'
[3802360c-03c0-411d-b100-9af886a64112] app/controllers/todos_controller.rb:121:in `create'
```

This doesn't happen for adding issues on a project page, for the record.

**Comment by ZeiP** [comment]
Thanks! I have to admit I haven't tested these functions in a while as I haven't (knowingly) made any changes to them since taking over the project. I'll take a look – it seems at least these two should've also been catched in automatic testing, so I'll try to include these in them as well. Probably won't be such a quick fix as with the recurring todos UI, though :)

**Comment by GregSutcliffe** [comment]
> Probably won't be such a quick fix as with the recurring todos UI, though :)

Heh, no problem, at least the edit/addition is saved, makes it less serious. I'll take a look if I get a chance, although it has been *quite some time* (083fe42b5ce2c8f80a08ac35dfcdf13043c5d393) since I last looked at the Tracks codebase :P

**Comment by GregSutcliffe** [comment]
Confirm fixed - thanks for the fast fix!
