### ISSUE TITLE
Editing an due date from the calendar causes server error

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2472]
(This *might* be related to #2471, not sure...)

Go to Views -> Calendar. See an item due today, decide to make it due tomorrow instead, so edit and change Due Date. On save, I get a server error, although the edit *is* saved (same as 2471, I guess) .

Server log is slightly different though:
```
I, [2020-09-01T14:22:24.598972 #1]  INFO -- : [3a09f3fd-6086-4156-acf6-7b696933ea76] Started PATCH "/todos/18" for 172.20.10.155 at 2020-09-01 14:22:24 +0000
I, [2020-09-01T14:22:24.600132 #1]  INFO -- : [3a09f3fd-6086-4156-acf6-7b696933ea76] Processing by TodosController#update as JS
I, [2020-09-01T14:22:24.600286 #1]  INFO -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[redacted]", "todo"=>{"id"=>"18", "description"=>"mow lawn", "notes"=>"", "due"=>"2020-09-02", "show_from"=>""}, "_source_view"=>"calendar", "_tag_name"=>"", "project_name"=>"", "context_name"=>"garden", "tag_list"=>"garden", "predecessor_input"=>"", "predecessor_list"=>"", "_group_view_by"=>"context", "id"=>"18"}
D, [2020-09-01T14:22:24.602802 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.605107 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Preference Load (0.6ms)  SELECT "preferences".* FROM "preferences" WHERE "preferences"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.608978 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Todo Load (1.0ms)  SELECT "todos".* FROM "todos" WHERE "todos"."user_id" = $1 AND "todos"."id" = $2 ORDER BY todos.completed_at DESC, todos.created_at DESC LIMIT $3  [["user_id", 1], ["id", 18], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.612592 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]    (0.4ms)  BEGIN
D, [2020-09-01T14:22:24.613795 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Tag Load (0.9ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2  [["taggable_id", 18], ["taggable_type", "Todo"]]
D, [2020-09-01T14:22:24.614788 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.616362 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Tag Load (0.7ms)  SELECT "tags".* FROM "tags" WHERE "tags"."user_id" = $1  [["user_id", 1]]
D, [2020-09-01T14:22:24.618017 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]    (0.4ms)  COMMIT
D, [2020-09-01T14:22:24.620086 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Tag Load (1.0ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "tags"."id" = "taggings"."tag_id" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2  [["taggable_id", 18], ["taggable_type", "Todo"]]
D, [2020-09-01T14:22:24.622617 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Context Load (0.9ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."user_id" = $1 AND "contexts"."name" = $2 ORDER BY position ASC LIMIT $3  [["user_id", 1], ["name", "garden"], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.625350 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]    (0.5ms)  BEGIN
D, [2020-09-01T14:22:24.626286 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Context Load (0.6ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.628696 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Todo Update (0.8ms)  UPDATE "todos" SET "due" = $1, "updated_at" = $2 WHERE "todos"."id" = $3  [["due", "2020-09-01 23:00:00"], ["updated_at", "2020-09-01 14:22:24.627090"], ["id", 18]]
D, [2020-09-01T14:22:24.631728 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Todo Load (0.9ms)  SELECT "todos".* FROM "todos" INNER JOIN "dependencies" ON "todos"."id" = "dependencies"."predecessor_id" WHERE "dependencies"."successor_id" = $1  [["successor_id", 18]]
D, [2020-09-01T14:22:24.633573 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Context Update (0.8ms)  UPDATE "contexts" SET "updated_at" = $1 WHERE "contexts"."id" = $2  [["updated_at", "2020-09-01 14:22:24.629286"], ["id", 6]]
D, [2020-09-01T14:22:24.644744 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]    (10.9ms)  COMMIT
D, [2020-09-01T14:22:24.646841 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Todo Load (0.6ms)  SELECT "todos".* FROM "todos" WHERE "todos"."id" = $1 LIMIT $2  [["id", 18], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.649179 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   Context Load (0.7ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
D, [2020-09-01T14:22:24.650396 #1] DEBUG -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   CACHE Context Load (0.0ms)  SELECT "contexts".* FROM "contexts" WHERE "contexts"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
I, [2020-09-01T14:22:24.651595 #1]  INFO -- : [3a09f3fd-6086-4156-acf6-7b696933ea76] Completed 500 Internal Server Error in 51ms (ActiveRecord: 22.3ms | Allocations: 7725)
F, [2020-09-01T14:22:24.667029 #1] FATAL -- : [3a09f3fd-6086-4156-acf6-7b696933ea76]   
[3a09f3fd-6086-4156-acf6-7b696933ea76] Exception (unknown due id for calendar: ''):
[3a09f3fd-6086-4156-acf6-7b696933ea76]   
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:1157:in `count_old_due_empty'
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:1137:in `is_old_due_empty'
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:1279:in `block (2 levels) in determine_changes_by_this_update'
[3a09f3fd-6086-4156-acf6-7b696933ea76] lib/tracks/source_view.rb:21:in `method_missing'
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:1278:in `block in determine_changes_by_this_update'
[3a09f3fd-6086-4156-acf6-7b696933ea76] lib/tracks/source_view.rb:43:in `source_view'
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:1277:in `determine_changes_by_this_update'
[3a09f3fd-6086-4156-acf6-7b696933ea76] app/controllers/todos_controller.rb:458:in `update'
```

**Comment by GregSutcliffe** [comment]
Confirm fixed - thanks for the fast fix!
