### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by gtothill** [TracksApp/tracks#2590]
I think this is a database initialization problem but I cant be sure Im afraid.

I did this to install:
git clone https://github.com/TracksApp/tracks.git
cd trackstouch .use-docker
./script/setup
./script/server

Te server appears to start up and be listening on 3000 but with a database error:

`=> Booting Puma
=> Rails 6.0.3.4 application starting in production 
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Puma version: 5.2.1 (ruby 2.7.1-p83) ("Fettisdagsbulle")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 9
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2021-03-08T14:17:26.639667 #9]  INFO -- : [31456f01-27a1-4f31-82fa-9ffea2d7f6f5] Started GET "/" for 192.168.124.19 at 2021-03-08 14:17:26 +0000
I, [2021-03-08T14:17:26.653120 #9]  INFO -- : [31456f01-27a1-4f31-82fa-9ffea2d7f6f5] Processing by TodosController#index as HTML
I, [2021-03-08T14:17:26.656364 #9]  INFO -- : [31456f01-27a1-4f31-82fa-9ffea2d7f6f5] Redirected to http://mydomain.local:3000/login
I, [2021-03-08T14:17:26.656477 #9]  INFO -- : [31456f01-27a1-4f31-82fa-9ffea2d7f6f5] Filter chain halted as :login_or_feed_token_required rendered or redirected
I, [2021-03-08T14:17:26.666189 #9]  INFO -- : [31456f01-27a1-4f31-82fa-9ffea2d7f6f5] Completed 302 Found in 3ms (Allocations: 672)
I, [2021-03-08T14:17:26.674969 #9]  INFO -- : [c7af6882-39a7-4471-8f2f-0fef933e6dba] Started GET "/login" for 192.168.124.19 at 2021-03-08 14:17:26 +0000
I, [2021-03-08T14:17:26.675548 #9]  INFO -- : [c7af6882-39a7-4471-8f2f-0fef933e6dba] Processing by LoginController#login as HTML
D, [2021-03-08T14:17:26.713980 #9] DEBUG -- : [c7af6882-39a7-4471-8f2f-0fef933e6dba]    (0.4ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
I, [2021-03-08T14:17:26.715193 #9]  INFO -- : [c7af6882-39a7-4471-8f2f-0fef933e6dba] Completed 500 Internal Server Error in 40ms (ActiveRecord: 1.0ms | Allocations: 1914)
F, [2021-03-08T14:17:26.715794 #9] FATAL -- : [c7af6882-39a7-4471-8f2f-0fef933e6dba]   
[c7af6882-39a7-4471-8f2f-0fef933e6dba] ActiveRecord::StatementInvalid (Mysql2::Error: Table 'tracks.users' doesn't exist):
[c7af6882-39a7-4471-8f2f-0fef933e6dba]   
[c7af6882-39a7-4471-8f2f-0fef933e6dba] app/models/user.rb:146:in `no_users_yet?'
[c7af6882-39a7-4471-8f2f-0fef933e6dba] app/controllers/login_controller.rb:25:in `login'
I, [2021-03-08T14:18:23.960463 #9]  INFO -- : [1789a724-2010-4220-b0da-319b6b50c692] Started GET "/login" for 192.168.124.19 at 2021-03-08 14:18:23 +0000
I, [2021-03-08T14:18:23.961874 #9]  INFO -- : [1789a724-2010-4220-b0da-319b6b50c692] Processing by LoginController#login as HTML
I, [2021-03-08T14:18:23.966182 #9]  INFO -- : [1789a724-2010-4220-b0da-319b6b50c692] Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.3ms | Allocations: 582)
F, [2021-03-08T14:18:23.967883 #9] FATAL -- : [1789a724-2010-4220-b0da-319b6b50c692]   
[1789a724-2010-4220-b0da-319b6b50c692] ActiveRecord::StatementInvalid (Mysql2::Error: Table 'tracks.users' doesn't exist):
[1789a724-2010-4220-b0da-319b6b50c692]   
[1789a724-2010-4220-b0da-319b6b50c692] app/models/user.rb:146:in `no_users_yet?'
[1789a724-2010-4220-b0da-319b6b50c692] app/controllers/login_controller.rb:25:in `login'
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-03-08 14:19:24 +0000 ===
- Goodbye!
`

Would anyone be able to give me a pointer to this - it appears that none of the tables exist in the database?

I seem to remember that last time I tried this I had to initialize it but for the life of me I don't know if that is the case now!

Cheers

Geoff

**Comment by gtothill** [comment]
BTW - does this way of starting the server conflict with just starting the container in the normal way with docker-compose up -d ?

**Comment by gtothill** [comment]
My apologies - this was due to a reverse proxy error due to a temp domain I was using to access the server. Closing this issue.
