### ISSUE TITLE
The instructions for running with Docker compose result in a broken installation

### ISSUE THREAD

**Issue by pmbrandvold** [TracksApp/tracks#3063]
I was able to get the script/setup and script/server files to run after changing every reference to "docker-compose" to "docker compose" to reflect how the docker engine calls compose now. However, this resulted in an instance that runs but doesn't have a users table, apparently. After hitting localhost:3000 I can launch a login page that says "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

The container logs show:
WARN[0000] The "RAILS_ENV" variable is not set. Defaulting to a blank string.
WARN[0000] The "DATABASE_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] /mnt/c/Git/tracks/tracks-2.7.1/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 12/12
 ✔ db Pulled                                                                                16.4s
   ✔ 20e4dcae4c69 Pull complete                                                              7.5s
   ✔ 1c56c3d4ce74 Pull complete                                                              7.5s
   ✔ e9f03a1c24ce Pull complete                                                              7.6s
   ✔ 68c3898c2015 Pull complete                                                              7.8s
   ✔ 6b95a940e7b6 Pull complete                                                              7.8s
   ✔ 90986bb8de6e Pull complete                                                              7.9s
   ✔ ae71319cb779 Pull complete                                                              8.5s
   ✔ ffc89e9dfd88 Pull complete                                                              8.6s
   ✔ 43d05e938198 Pull complete                                                             15.1s
   ✔ 064b2d298fba Pull complete                                                             15.2s
   ✔ df9a4d85569b Pull complete                                                             15.2s
[+] Creating 3/3
 ✔ Network tracks-271_default   Created                                                      0.2s
 ✔ Volume "tracks-271_db-data"  Created                                                      0.0s
 ✔ Container tracks-271-db-1    Created                                                      0.5s
[+] Running 1/1
 ✔ Container tracks-271-db-1  Started                                                        0.5s
=> Booting Puma
=> Rails 6.1.7.8 application starting in production
=> Run `bin/rails server --help` for more startup options
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.3.5-p100) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 12
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop
I, [2024-09-11T20:44:05.608672 #12]  INFO -- : [6744efed-9bd9-4149-a176-63d5fdd47a44] Started GET "/" for 172.18.0.1 at 2024-09-11 20:44:05 +0000
I, [2024-09-11T20:44:05.618112 #12]  INFO -- : [6744efed-9bd9-4149-a176-63d5fdd47a44] Processing by TodosController#index as HTML
I, [2024-09-11T20:44:05.623425 #12]  INFO -- : [6744efed-9bd9-4149-a176-63d5fdd47a44] Redirected to http://localhost:3000/login
I, [2024-09-11T20:44:05.623567 #12]  INFO -- : [6744efed-9bd9-4149-a176-63d5fdd47a44] Filter chain halted as :login_or_feed_token_required rendered or redirected
I, [2024-09-11T20:44:05.623798 #12]  INFO -- : [6744efed-9bd9-4149-a176-63d5fdd47a44] Completed 302 Found in 6ms (Allocations: 816)
I, [2024-09-11T20:44:05.786540 #12]  INFO -- : [bd5c0336-48cd-405f-8440-eaba3d40e04f] Started GET "/login" for 172.18.0.1 at 2024-09-11 20:44:05 +0000
I, [2024-09-11T20:44:05.787364 #12]  INFO -- : [bd5c0336-48cd-405f-8440-eaba3d40e04f] Processing by LoginController#login as HTML
I, [2024-09-11T20:44:05.803149 #12]  INFO -- : [bd5c0336-48cd-405f-8440-eaba3d40e04f] Completed 500 Internal Server Error in 16ms (ActiveRecord: 1.0ms | Allocations: 2807)
F, [2024-09-11T20:44:05.803655 #12] FATAL -- : [bd5c0336-48cd-405f-8440-eaba3d40e04f]
[bd5c0336-48cd-405f-8440-eaba3d40e04f] ActiveRecord::StatementInvalid (Mysql2::Error: Table 'tracks.users' doesn't exist):
[bd5c0336-48cd-405f-8440-eaba3d40e04f]
[bd5c0336-48cd-405f-8440-eaba3d40e04f] app/models/user.rb:146:in `no_users_yet?'
[bd5c0336-48cd-405f-8440-eaba3d40e04f] app/controllers/login_controller.rb:25:in `login'
I, [2024-09-11T20:44:11.465095 #12]  INFO -- : [7c80c1b7-a8f6-4d45-939b-832e9c08689e] Started GET "/login" for 172.18.0.1 at 2024-09-11 20:44:11 +0000
I, [2024-09-11T20:44:11.465583 #12]  INFO -- : [7c80c1b7-a8f6-4d45-939b-832e9c08689e] Processing by LoginController#login as HTML
I, [2024-09-11T20:44:11.467425 #12]  INFO -- : [7c80c1b7-a8f6-4d45-939b-832e9c08689e] Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.6ms | Allocations: 531)
F, [2024-09-11T20:44:11.468088 #12] FATAL -- : [7c80c1b7-a8f6-4d45-939b-832e9c08689e]
[7c80c1b7-a8f6-4d45-939b-832e9c08689e] ActiveRecord::StatementInvalid (Mysql2::Error: Table 'tracks.users' doesn't exist):

It's clear there is' a missing table (tracks.users) but as far as the instructions say, things should be working after running the scripts.

Beyond this issue, there's no really effective way for me to run this in something like portainer, because it requires me to run a bunch of separate scripts to manipulate the docker file and container instances. Is there an easier way to do this? I have an old version of tracks working but it's using Stannoe's docker image which is outdated. Ultimately I just want to update my current instance but I'm stuck until I have a way to set things up with the latest code...

**Comment by topcu-muhammet** [comment]
Same here. Is there any solution?

**Comment by pmbrandvold** [comment]
What would be easier is if I could just use the tracksapp/tracks image, but there's no documentation on how to set that up in a compose stack. It seems as though it requires a database, which makes sense. But there's no documentation on how to set a database up to be used with the tracksapp/tracks image (which is presumably just a frontend? I'm not sure). When I just pull "tracksapp/tracks" and run it, I get an error that seems to be from no user existing yet, but there's no instructions on how to set up a user.

**Comment by gauravagnihotristla** [comment]
what worked for me - 
try version 2.7.0.tar.gz 
I use this on my personal server proxmox - container ubuntu24.04 
edit Dockerfile and make [this small change](https://github.com/TracksApp/tracks/pull/3037/commits/d2fff6a64c4988744f0f164ce9ccfa8a3481b648#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)

after that it was as easy as 
```
./script/setup 
./script/server
```
